# Generated by Django 4.1.1 on 2022-10-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_time',
            new_name='date_time',
        ),
    ]
