# Generated by Django 4.2 on 2023-11-21 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_order_requestdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='farmer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.inventoryitem'),
        ),
    ]
