# Generated by Django 4.2 on 2023-11-21 21:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_inventoryitem_alter_order_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_time',
        ),
        migrations.AddField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 22, 28, 445785, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 22, 28, 445083, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 22, 28, 445998, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
