# Generated by Django 4.2 on 2023-11-21 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0012_remove_post_date_time_post_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 23, 16, 64302, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 23, 16, 65137, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 23, 16, 65344, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
