# Generated by Django 4.2 on 2023-11-21 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_alter_inventoryitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='quantity_available',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 1, 5, 620056, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 1, 5, 620758, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
