# Generated by Django 4.2 on 2023-11-21 22:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0014_rename_quantity_available_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='farmer_name',
            field=models.CharField(default='Rachana', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='farmer_name',
            field=models.CharField(default='Rachana', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 20, 6, 118728, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 20, 6, 119391, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
