# Generated by Django 4.2 on 2023-11-21 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0015_inventoryitem_farmer_name_inventoryitem_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 37, 36, 222753, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 37, 36, 223485, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
