# Generated by Django 4.2 on 2023-11-30 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0016_alter_post_expiry_date_alter_requestdata_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 2, 56, 51, 398064, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 2, 56, 51, 399041, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
