# Generated by Django 4.2 on 2023-11-30 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_inventoryitem_availability_alter_post_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 4, 41, 20, 716655, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 4, 41, 20, 717317, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
