# Generated by Django 4.2 on 2023-11-30 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0018_inventoryitem_image_alter_post_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 4, 44, 33, 655120, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 4, 44, 33, 655559, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
