# Generated by Django 4.2 on 2023-11-30 23:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0019_remove_inventoryitem_image_alter_post_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer_name', models.CharField(max_length=160)),
                ('product_name', models.CharField(max_length=160)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2023, 12, 30, 23, 28, 1, 901288, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=160)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestData',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 23, 28, 1, 900527, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
